-- CREATING DATABASE 
CREATE DATABASE TECHMACK_DB;
-- USING DATABASE 
USE TECHMACk_DB;

-- CREATING TABLE 

CREATE TABLE TECHYVE_EMPLOYEE(
EMPLOYE_ID int,
FIRST_NAME VARCHAR (255),
LAST_NAME VARCHAR(255),
GENDER enum('male','female','other'),
AGE INT);
-- ALTER& MODIFY EMPLOYE_ID VARCHAR (100)
ALTER TABLE TECHYVE_EMPLOYEE MODIFY EMPLOYE_ID varchar(100);
-- ALTER TABLE ADDING PERFEENSY 
ALTER TABLE TECHYVE_EMPLOYEE
ADD PERFENSY INT;
-- describeTABLE 
DESC  TECHYVE_EMPLOYEE;
-- ALTER TABLE ADDING PRIMARY KEY IN EMPLOYEE ID COLUMN 

ALTER TABLE TECHYVE_EMPLOYEE ADD primary key(EMPLOYE_ID);

-- ALTER TABLE AND MODIFYING EMPLOYE ID BETWEEN 1 AND 5

ALTER TABLE TECHYVE_EMPLOYEE modify  PERFENSY INT CHECK ( PERFENSY  between 1 AND 5);
-- ALTER & MODIFY EMPLOYE_ID INT TO VARCHAR 
alter table TECHYVE_EMPLOYEE modify column EMPLOYE_ID varchar(100);
-- DROPING DATABASE 
DROP TABLE TECHYVE_EMPLOYEE;
-- describe
DESC TECHYVE_EMPLOYEE;
DESC TECHYVE_EMPLOYEE;
-- ALTER TABLE ECHYVE_EMPLOYE & MODIFY AGE 
alter TABLE  TECHYVE_EMPLOYEE MODIFY AGE INT CHECK (AGE between 21 AND 50);

--- MODIFY INT TO VARCHAR 

ALTER TABLE TECHYVE_EMPLOYEE modify column EMPLOYE_ID varchar(100);
-- describe TABLE 
DESC TECHYVE_EMPLOYEE;
-- INSERTING VALUES INTO TABLE 
INSERT INTO TECHYVE_EMPLOYEE (EMPLOYE_ID,FIRST_NAME,LAST_NAME,GENDER,AGE,PERFENSY)
VALUES ("TH0001","Eli","Evans","Male",26,1),
("TH0002","Carlos","Simmons","Male",32,2),
("TH0003","Kathie","Bryant","Female",25,1),
("TH0004","Joey","Hughes","Male",41,4),
("TH0005","Alice","Matthews","Female",52,4);


select*from TECHYVE_EMPLOYEE;

-- ADDING CLONE AND CHANGING NAME OF TABLE 

create table TECHYVE_EMPLOYEE_bkp like TECHYVE_EMPLOYEE;

-- DELETING DATA FROM EMPLOYE 

DELETE FROM TECHYVE_EMPLOYEE
WHERE EMPLOYE_ID IN ('TS0001', 'TS0003', 'TS0004', 'TS0005');

-- CREATING TABLE 2

CREATE TABLE TACKCLOUD_EMPLOYES(EMPLOYE_ID int,
FIRST_NAME VARCHAR (255),
LAST_NAME VARCHAR(255),
GENDER enum('male','female','other'),
AGE INT);

-- ALTER TABLE TACKCLOUD_EMPLOYES ADD PRIFANCY 

ALTER TABLE TACKCLOUD_EMPLOYES
ADD  PERFENSY INT;
-- ALTER TABLE ADDING PRIMARY KEY 
ALTER TABLE TACKCLOUD_EMPLOYES ADD primary key(EMPLOYE_ID);
-- ALTER TABLE & MODIFY PERFANCY & GENDER  INT TO BETWEEN 
ALTER TABLE TACKCLOUD_EMPLOYES MODIFY PERFENSY  INT check (PERFENSY  between 1 AND 5);
ALTER TABLE TACKCLOUD_EMPLOYES modify AGE INT CHECK (AGE between 21 AND 55);
-- ALTER TABLE & MODIFY EMPLOYE ID INT TO VARCHAR 
ALTER TABLE TACKCLOUD_EMPLOYES MODIFY EMPLOYE_ID VARCHAR (100);
-- INSERTING VALUES INTO TABLE 
INSERT INTO TACKCLOUD_EMPLOYES(EMPLOYE_ID,FIRST_NAME,LAST_NAME,GENDER,AGE,PERFENSY)
values("TC0001","Teresa","Bryant","Female",39,2),
("TC0002","Alexis","Patterson","Male",48,5),
("TC0003","Rose","Bell","Female",42,3),
("TC0004","Gemma","Watkins","Female",44,3),
("TC0005","Kingston","Martinez","Male",29,2);
SELECT *FROM TACKCLOUD_EMPLOYES;
-- ADIING COLUN CHANGING TABLE NAME 
create table TACKCLOUD_EMPLOYES_bkp like TACKCLOUD_EMPLOYES ;

-- DESCRIVE TABLE 2

DESC  TACKCLOUD_EMPLOYES;
DROP TABLE TACKCLOUD_EMPLOYES;
 -- DELETE DATA FROM EMPLOYE 
DELETE FROM TACKCLOUD_EMPLOYES
WHERE EMPLOYE_ID IN ('TS0001', 'TS0003', 'TS0004', 'TS0005');
CREATE TABLE TECHYVECLOUD_EMPLOYEES LIKE  TACKCLOUD_EMPLOYES;
INSERT INTO TECHYVECLOUD_EMPLOYEES (EMPLOYE_ID,FIRST_NAME,LAST_NAME,GENDER,AGE,PERFENSY)
select EMPLOYE_ID,FIRST_NAME,LAST_NAME,GENDER,AGE,PERFENSY from TECHYVECLOUD_EMPLOYEES
union
select EMPLOYE_ID,FIRST_NAME,LAST_NAME,GENDER,AGE,PERFENSY from TACKCLOUD_EMPLOYES;

-- CREATING TABLE 3 

CREATE TABLE TACSOFT_EMPLOYE(
EMPLOYE_ID int,
FIRST_NAME VARCHAR (255),
LAST_NAME VARCHAR(255),
GENDER enum('male','female','other'),
AGE INT);

-- ALTER TABLE & ADD PARFENCY 

ALTER TABLE TACSOFT_EMPLOYE
ADD PERFENSY INT;
ALTER TABLE TACSOFT_EMPLOYE ADD primary key(EMPLOYE_ID);

-- ALTER & MODIFY EMPLOYE ID 

ALTER TABLE TACSOFT_EMPLOYE modify  PERFENSY INT CHECK (PERFENSY between 1 AND 5);

-- ALTER & MODIFY AGE 

ALTER TABLE TACSOFT_EMPLOYE MODIFY AGE INT CHECK (AGE between 21 AND 55);
desc TACSOFT_EMPLOYE;
desc TACSOFT_EMPLOYE;
DROP database EMPLOYE_ID;
DROP TABLE TACSOFT_EMPLOYE;
-- INSERTING VALUES INTO TABLE 
INSERT INTO TACSOFT_EMPLOYE (EMPLOYE_ID,FIRST_NAME ,LAST_NAME ,GENDER ,AGE,PERFENSY)
VAlues ("TS0001","Peter","Burtler","Male",44,4),
("TS0002","Harold","Simmons","Male",54,4),
("TS0003","Juliana","Sanders","Female",36,2),
("TS0004","Paul","Ward","Male",29,2),
("TS0005","Nicole","Bryant","Female",30,2);

ALTER TABLE TACSOFT_EMPLOYE MODIFY EMPLOYE_ID VARCHAR (100);
select*from TACSOFT_EMPLOYE;
ALTER TABLE TACKCLOUD_EMPLOYES MODIFY EMPLOYE_ID VARCHAR(100);
create table TACSOFT_EMPLOYE_bkp like TACSOFT_EMPLOYE;
SELECT * FROM TACSOFT_EMPLOYE;

-- DELATE DATA FROM EMPLOYE ID 
DELETE FROM TACSOFT_EMPLOYE
WHERE EMPLOYE_ID IN ('TS0001', 'TS0003', 'TS0004', 'TS0005');
SELECT * FROM TACSOFT_EMPLOYE;

truncate table TACKCLOUD_EMPLOYES ,TECHYVE_EMPLOYEE;
